Repository paketo-buildpacks/nginx, pull requests merged in 2022-10, with the labels that each got.

#436 Tidy Up
  build.go
  build_test.go
  cmd/configure/internal/run_test.go
  default_config_generator_test.go
  detect_test.go
  fakes/entry_resolver.go
  go.mod
  go.sum
  integration/require_test.go
  integration/simple_app_test.go
  parser_test.go
  run/main.go
Labels: semver:patch

#437 Use occam matcher BeAFileMatching
  cmd/configure/internal/run_test.go
  default_config_generator_test.go
  integration/simple_app_test.go
Labels: status/blocked, semver:patch

#446 Adds longer polling interval to lighten resource burden
  integration/init_test.go
Labels: semver:patch

#431 Dep manage
  .github/.syncignore
  .github/workflows/update-dependencies.yml
  buildpack.toml
  dependency/Makefile
  dependency/actions/compile/README.md
  dependency/actions/compile/action.yml
  dependency/actions/compile/bionic.Dockerfile
  dependency/actions/compile/entrypoint
  dependency/actions/compile/jammy.Dockerfile
  dependency/retrieval/go.mod
  dependency/retrieval/go.sum
  dependency/retrieval/retrieve.go
  dependency/test/bionic/Dockerfile
  dependency/test/bionic/entrypoint
  dependency/test/bionic/fixtures/index.html
  dependency/test/bionic/fixtures/nginx.conf
  dependency/test/fixtures/index.html
  dependency/test/fixtures/nginx.conf
  dependency/test/jammy/Dockerfile
  dependency/test/jammy/entrypoint
  dependency/test/jammy/fixtures/index.html
  dependency/test/jammy/fixtures/nginx.conf
  dependency/test/run-test
Labels: semver:minor

#456 Fix malformed checksum in retrieval and compile
  dependency/actions/compile/entrypoint
  dependency/retrieval/retrieve.go
Labels: semver:patch

#411 Adds support for jammy
  buildpack.toml
  integration.json
Labels: semver:minor
